import turtle
# turtle.shape('turtle')
turtle.speed(1)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.left(90)
turtle.pendown()
turtle.forward(100)
turtle.forward(30)
turtle.penup()

turtle.exitonclick()
